apiVersion: v1
kind: Namespace
metadata:
  name: cloudwatch
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cloudwatch-healthcheck
  name: cloudwatch-healthcheck
  namespace: cloudwatch
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cloudwatch-healthcheck
  template:
    metadata:
      labels:
        app: cloudwatch-healthcheck
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: ghcr.io/william86370/cloudwatch-healthcheck:latest
        imagePullPolicy: Always
        name: cloudwatch-healthcheck
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICEACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
        ports:
        - containerPort: 8080
          name: healthcheck
          protocol: TCP
      initContainers:
        - image: ghcr.io/william86370/cloudwatch-healthcheck-init:latest
          imagePullPolicy: Always
          name: cloudwatch-healthcheck-init
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICEACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      dnsPolicy: ClusterFirst
      serviceAccount: cloudwatch-privileged
      serviceAccountName: cloudwatch-privileged
      terminationGracePeriodSeconds: 10