# We love RBAC and we use it to manage permissions
# RIP PSP V1.25 - Will W
# This Reminds me of PERMISSIONS EX - Will W

apiVersion: v1
kind: Namespace
metadata:
  name: cloudwatch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: cloudwatch
 name: cloudwatch-privileged-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: cloudwatch-privileged-binding
 namespace: cloudwatch
subjects:
- kind: ServiceAccount
  name: cloudwatch-privileged
  namespace: cloudwatch
roleRef:
 kind: Role
 name: cloudwatch-privileged-role
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudwatch-privileged-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - daemonSets
  verbs:
  - get
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: cloudwatch-privileged-cluster-binding
subjects:
- kind: ServiceAccount
  name: cloudwatch-privileged
  namespace: cloudwatch
roleRef:
 kind: ClusterRole
 name: cloudwatch-privileged-cluster-role
 apiGroup: rbac.authorization.k8s.io
---
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: "cloudwatch-privileged"
   namespace: cloudwatch