apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-dev-init
  labels:
    app: cloudwatch-dev-init
  namespace: cloudwatch
spec:
  selector:
    matchLabels:
      app: cloudwatch-dev-init
  template:
    metadata:
      labels:
        app: cloudwatch-dev-init
    spec:
      serviceAccount: cloudwatch-init-account
      serviceAccountName: cloudwatch-init-account
      containers:
        - imagePullPolicy: Always
          name: cloudwatch-healthcheck-init
          image: ghcr.io/william86370/cloudwatch-healthcheck-init:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICEACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName