apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudwatch-operator
  name: cloudwatch-operator
  namespace: cloudwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-operator
  template:
    metadata:
      labels:
        app: cloudwatch-operator
    spec:
      containers:
      - env:
        - name: CLOUDWATCH_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ghcr.io/william86370/cloudwatch-operator
        imagePullPolicy: Always
        name: cloudwatch-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: cloudwatch-privileged
      serviceAccountName: cloudwatch-privileged